#include<iostream> 
using namespace std;
int INT_MAX;
int getMin(int num [] , int n) {
   int min = INT_MAX;
    for( int i=0; i<=n; i++) {
        if ( num [i] < min) {
            min = num [i];

        }
    }
    return min;

}
int INT_MIN;
int getMax(int num [] , int n) {
    int max  = INT_MIN;
    for( int i = 0; i<=n; i++) {
        if ( num[i] > max) {
            max = num [i];

        }
    }
    return max;

}


int main() {
    int size;
    cin>>size;
    int num [10] = {55,66,88,99,22,29,36,14,85,96};
    for( int i = 0; i< size; i++) {
        cin>> num [i];
        cout<<" minimum value is "<<" "<< getMin(num, size)<<endl;
        cout<<" maximum value is "<<" "<< getMax(num, size)<<endl;
        return 0;


    }
}